Repository githru/githru-feature-practices, pull requests merged in 2022-07, with the labels that each got.

#22 feat: :sparkles: (WIP) git log to json parser 구현
  parser/hy57in/.eslintignore
  parser/hy57in/.eslintrc.json
  parser/hy57in/.gitignore
  parser/hy57in/.prettierrc.js
  parser/hy57in/README.md
  parser/hy57in/__test__/sum.test.ts
  parser/hy57in/package.json
  parser/hy57in/scripts/build.js
  parser/hy57in/src/index.ts
  parser/hy57in/src/sum.ts
  parser/hy57in/tsconfig.json
  parser/hy57in/yarn.lock
Labels: ✨ feature

#11 docs: readme 추가
  linechart/ag502/README.md
Labels: documentation

#7 feat: Vite react-ts boilerplate
  linechart/hyeda1103/.eslintignore
  linechart/hyeda1103/.eslintrc.json
  linechart/hyeda1103/.gitignore
  linechart/hyeda1103/.npmrc
  linechart/hyeda1103/.prettierrc
  linechart/hyeda1103/README.md
  linechart/hyeda1103/index.html
  linechart/hyeda1103/package.json
  linechart/hyeda1103/pnpm-lock.yaml
  linechart/hyeda1103/public/vite.svg
  linechart/hyeda1103/src/App.tsx
  linechart/hyeda1103/src/main.tsx
  linechart/hyeda1103/src/vite-env.d.ts
  linechart/hyeda1103/tsconfig.json
  linechart/hyeda1103/tsconfig.node.json
  linechart/hyeda1103/vite.config.ts
Labels: enhancement

#12 DOC:readme추가
  linechart/kmin-jeong/README.md
  parser/kmin-jeong/README.md
Labels: documentation

#21 docs: add `README.md`
  icicle/jeonghye-choi/README.md
Labels: documentation
